### ISSUE TITLE
Please rename the tutorial to avoid confusion with official documentation provided by EIDF

### ISSUE THREAD

**Issue by ugermann** [AntreasAntoniou/EIDF-tutorial#1]
As per request by the EIDF folks regarding to avoid confusion due to naming convention, could you rename the tutorial?

My suggestion would be to refer to our slice of the EIDF GPU cluster simply as infk8s (or uedin-infk8s, or infk8s-at-eidf).

So infk8s-tutorial would be one option.

**Comment by AntreasAntoniou** [comment]
Done!
